openapi: 3.0.3
info:
  title: WanderWise - OpenAPI 3.0
  description: A simple wander-wise API definition
  termsOfService: http://swagger.io/terms/
  contact:
    name: WanderWise
    email: info@wanderwise.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
- url: 'http://localhost:8080'
tags:
- name: User
  description: Operations about User
- name: Landmarks
  description: Operations about Landmarks
- name: Reviews
  description: Operations about Reviews
- name: Experiences
  description: Operations about Experiences
- name: Photos
  description: Operations about Photos
- name: Interactive_map
  description: Operations about Interactive Map
paths:
  /user:
    post:
      tags:
      - User
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
      x-swagger-router-controller: User
  /user/createWithList:
    post:
      tags:
      - User
      summary: Creates list of users with given input array
      description: Creates list of users with given input array
      operationId: createUsersWithListInput
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: successful operation
      x-swagger-router-controller: User
  /user/login:
    get:
      tags:
      - User
      summary: Logs user into the system
      description: ""
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              style: simple
              explode: false
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              style: simple
              explode: false
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
                x-content-type: application/xml
            application/json:
              schema:
                type: string
        "400":
          description: Invalid username/password supplied
      x-swagger-router-controller: User
  /user/logout:
    get:
      tags:
      - User
      summary: Logs out current logged in user session
      description: ""
      operationId: logoutUser
      parameters: []
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: User
  /user/{username}:
    get:
      tags:
      - User
      summary: Get user by user name
      description: ""
      operationId: getUserByName
      parameters:
      - name: username
        in: path
        description: 'The name that needs to be fetched. Use user1 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
      x-swagger-router-controller: User
    put:
      tags:
      - User
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
      - name: username
        in: path
        description: name that need to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: User
    delete:
      tags:
      - User
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
      - name: username
        in: path
        description: The name that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
      x-swagger-router-controller: User
  /landmarks:
    post:
      tags:
      - Landmarks
      summary: Create a landmark
      description: |
        FR6: Add landmark
      operationId: createLandmark
      requestBody:
        description: Created landmark object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Landmark'
          application/xml:
            schema:
              $ref: '#/components/schemas/Landmark'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Landmark'
      responses:
        '201':
          description: Landmark Created!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landmark'
            application/xml:
              schema:
                $ref: '#/components/schemas/Landmark'
      x-swagger-router-controller: Landmarks
  /landmarks/{landmarkId}:
    get:
      tags:
      - Landmarks
      summary: Get landmark by landmark id
      description: ""
      operationId: getLandmarkById
      parameters:
      - name: landmarkId
        in: path
        description: 'The name that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Landmark Found!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landmark'
            application/xml:
              schema:
                $ref: '#/components/schemas/Landmark'
        "400":
          description: Invalid landmarkId supplied
        "404":
          description: Landmark Not Found!
      x-swagger-router-controller: Landmarks
    delete:
      tags:
      - Landmarks
      summary: Delete a landmark
      description: |
        FR7: Remove landmark
      operationId: deleteLandmark
      parameters:
      - name: landmarkId
        in: path
        description: Landmark id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid landmark id value
      security:
      - landmarks_auth:
        - write:landmarks
        - read:landmarks
      x-swagger-router-controller: Landmarks
  /landmarks/{landmarkId}/reviews:
    get:
      tags:
      - Reviews
      summary: Get reviews for the current landmark
      description: |
        FR3: View review
      operationId: getReviewsForLandmark
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 348
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewsArray'
            application/xml:
              schema:
                $ref: '#/components/schemas/ReviewsArray'
        "400":
          description: Invalid landmarkId supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input
                  message:
                    type: string
                    example: landmarkId is not valid. Please try a positive integer.
        "404":
          description: Reviews not found
      x-swagger-router-controller: Reviews
    post:
      tags:
      - Reviews
      summary: Create a review
      description: |
        FR1: Add a review
      operationId: addReview
      parameters:
      - name: landmarkId
        in: path
        description: 'The id of the landmark for which the review is being added. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
      requestBody:
        description: Review
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewForRequestBody'
        required: true
      responses:
        '201':
          description: Review created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewForRequestBody'
        '400':
          description: Bad request. The review data or landmarkId is invalid.
      x-swagger-router-controller: Reviews
  /landmarks/{landmarkId}/reviews/{reviewId}:
    get:
      tags:
      - Reviews
      summary: Get review by review id
      description: |
        FR3: View a review
      operationId: getReviewsById
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 348
      - name: reviewId
        in: path
        description: 'The id that needs to be fetched. Use 23 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 23
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
            application/xml:
              schema:
                $ref: '#/components/schemas/Review'
        "400":
          description: Invalid reviewId supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input
                  message:
                    type: string
                    example: landmarkId is not valid. Please try a positive integer.
        "404":
          description: Review not found
      x-swagger-router-controller: Reviews
    delete:
      tags:
      - Reviews
      summary: Delete a review created by the user
      description: |
        FR2: Delete a review
      operationId: deleteReview
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 348
      - name: reviewId
        in: path
        description: 'The id that needs to be fetched. Use 23 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 23
      responses:
        "200":
          description: Successful Operation - Successful Deletion
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The review has been successfully deleted.
        "400":
          description: Unsuccessful Operation
      security:
      - reviews_auth:
        - write:reviews
        - read:reviews
      x-swagger-router-controller: Reviews
  /landmarks/{landmarkId}/reviews/{reviewId}/numOfStars:
    post:
      tags:
      - Reviews
      summary: Evaluate a review
      description: |
        FR10: Evaluate a review
      operationId: evaluateReview
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 348
      - name: reviewId
        in: path
        description: 'The id that needs to be fetched. Use 23 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 23
      requestBody:
        description: Review
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        '201':
          description: Number of stars successfully updated!
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Bad Request
      x-swagger-router-controller: Reviews
  /landmarks/{landmarkId}/reviews/{reviewId}/comments:
    get:
      tags:
      - Landmarks
      summary: Get comments for current landmark review
      description: |
        FR12: Reply to reviews and comments
      operationId: getCommentsForReview
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 348
      - name: reviewId
        in: path
        description: 'The id that needs to be fetched. Use 23 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 23
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landmark'
            application/xml:
              schema:
                $ref: '#/components/schemas/Landmark'
        "400":
          description: Invalid landmarkId supplied
        "404":
          description: Landmark not found
      x-swagger-router-controller: Landmarks
    post:
      tags:
      - Comments
      summary: Create a comment
      description: |
        FR1: Add a review
      operationId: addComment
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 348
      - name: reviewId
        in: path
        description: 'The id that needs to be fetched. Use 23 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 23
      requestBody:
        description: Review
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        "200":
          description: review response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
      x-swagger-router-controller: Comments
  /landmarks/{landmarkId}/reviews/{reviewId}/comments/{commentId}:
    get:
      tags:
      - Landmarks
      summary: Get comment by comment id
      description: ""
      operationId: getCommentById
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 348
      - name: reviewId
        in: path
        description: 'The id that needs to be fetched. Use 23 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 23
      - name: commentId
        in: path
        description: 'The id that needs to be fetched. Use 2 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 2
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landmark'
            application/xml:
              schema:
                $ref: '#/components/schemas/Landmark'
        "400":
          description: Invalid landmarkId supplied
        "404":
          description: Landmark not found
      x-swagger-router-controller: Landmarks
    delete:
      tags:
      - Comments
      summary: Delete a comment
      operationId: deleteComment
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: reviewId
        in: path
        description: 'The id that needs to be fetched. Use 23 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: commentId
        in: path
        description: 'The id that needs to be fetched. Use 2 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid comment id value
      security:
      - comments_auth:
        - write:comments
        - read:comments
      x-swagger-router-controller: Comments
  /landmarks/{landmarkId}/photos:
    get:
      tags:
      - Photos
      summary: Get photos for the current landmark
      description: ""
      operationId: getPhotosForLandmark
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Photo'
            application/xml:
              schema:
                $ref: '#/components/schemas/Photo'
        "400":
          description: Invalid photoId supplied
        "404":
          description: Photo not found
      x-swagger-router-controller: Photos
    post:
      tags:
      - Photos
      summary: Add a photo
      description: |
        FR8: Add photos of landmark
      operationId: addPhoto
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Photo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Photo'
        required: true
      responses:
        "200":
          description: photo response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Photo'
      x-swagger-router-controller: Photos
  /landmarks/{landmarkId}/photos/{photoId}:
    delete:
      tags:
      - Photos
      summary: Delete a photo added by the user
      description: |
        FR9: Remove photos of landmark
      operationId: deletePhoto
      parameters:
      - name: landmarkId
        in: path
        description: 'The id that needs to be fetched. Use 348 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: photoId
        in: path
        description: 'The id that needs to be fetched. Use 8 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid photo id value
      security:
      - photos_auth:
        - write:photos
        - read:photos
      x-swagger-router-controller: Photos
  /experiences:
    post:
      tags:
      - Experiences
      summary: Create an experience
      description: |
        FR5: Create an Experience
      operationId: createExperience
      requestBody:
        description: Created experience object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Experience'
          application/xml:
            schema:
              $ref: '#/components/schemas/Experience'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Experience'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Experience'
            application/xml:
              schema:
                $ref: '#/components/schemas/Experience'
      x-swagger-router-controller: Experiences
  /experiences/{experienceId}:
    get:
      tags:
      - Experiences
      summary: Get experience by experience id
      description: ""
      operationId: getExperienceById
      parameters:
      - name: experienceId
        in: path
        description: 'The name that needs to be fetched. Use 4 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Experience'
            application/xml:
              schema:
                $ref: '#/components/schemas/Experience'
        "400":
          description: Invalid experienceId supplied
        "404":
          description: Experience not found
      x-swagger-router-controller: Experiences
    delete:
      tags:
      - Experiences
      summary: Delete an experience
      description: delete an experience
      operationId: deleteExperience
      parameters:
      - name: experienceId
        in: path
        description: Experience id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid experience id value
      security:
      - experiences_auth:
        - write:experiences
        - read:experiences
      x-swagger-router-controller: Experiences
  /experiences/{experienceId}/{landmarkId}:
    put:
      tags:
      - Experiences
      summary: Update experience
      description: This can only be done by the logged in user.
      operationId: updateExperience
      parameters:
      - name: landmarkId
        in: path
        description: landmark id that needs to be added
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: experienceId
        in: path
        description: experience id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Update an existent experience in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Experience'
          application/xml:
            schema:
              $ref: '#/components/schemas/Experience'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Experience'
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Experiences
  /interactive_map:
    get:
      tags:
      - Interactive_map
      summary: See/Interact interactive map
      description: This can only be done by the logged-in user.
      operationId: interactive_map
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Interactive_map'
            application/xml:
              schema:
                $ref: '#/components/schemas/Interactive_map'
      x-swagger-router-controller: InteractiveMap
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: "12345"
        phone:
          type: string
          example: "12345"
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
      example:
        firstName: John
        lastName: James
        password: "12345"
        userStatus: 1
        phone: "12345"
        id: 10
        email: john@email.com
        username: theUser
      xml:
        name: user
    Landmark:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 124
        name:
          type: string
          example: The White Tower
        details:
          type: string
          example: "Located near the city center, the White Tower is..."
        location:
          type: array
          items:
            type: string
            example: 40.753°N
        photos:
          $ref: '#/components/schemas/Landmark_photos'
        reviews:
          $ref: '#/components/schemas/Landmark_reviews'
      example:
        id: 124
        name: The White Tower
        details: "Located near the city center, the White Tower is..."
        location: [40.6264°N, 22.9483°E]
        photos:
          id: 212
          name: Top view of the Tower.
          date: 10th of August 2017
          image: [0, 255]
        reviews:
          date: 15th of November 2023
          review_id: 2
          numOfStars: 2
          comments: I agree with this review...
          review_text: This landmark is worth visiting, because...
      xml:
        name: landmark
    Photo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 16422
        name:
          type: string
          example: Top view of the Tower.
        image:
          type: array
          items:
            type: integer
            format: int64
            example: 255
        date:
          type: string
          example: 10th of August 2017
      example:
        date: 10th of August 2017
        image:
        - 255
        - 255
        name: Top view of the Tower.
        id: 16422
      xml:
        name: photo
    Review:
      type: object
      properties:
        review_id:
          type: integer
          format: int64
          example: 2
        review_text:
          type: string
          example: This landmark worths visiting...
        numOfStars:
          maximum: 5
          minimum: 1
          type: integer
          format: int64
          example: 2
        comments:
          $ref: '#/components/schemas/Review_comments'
        date:
          type: string
          example: 15th of November 2023
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 3
        text:
          type: string
          example: I loved the view from up there!
        author:
          type: string
          example: WiseWanderer
        date:
          type: string
          example: 9th of July 2024
      xml:
        name: comment
    Experience:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 234
        name:
          type: string
          example: My experience at the White Tower
        description:
          type: string
          example: "I had so much fun at the White Tower, because ..."
        landmarkId:
          type: integer
          format: int64
          example: 124
      example:
        landmarkId: 124
        name: My experience at the White Tower
        description: "I had so much fun at the White Tower, because ..."
        id: 234
      xml:
        name: experience
    Interactive_map:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Center of Thessaloniki
        area_shown:
          type: array
          items:
            $ref: '#/components/schemas/Interactive_Map_Entity'
        details:
          type: string
          example: "Located near the city center, the White Tower is..."
      example:
        name: Center of Thessaloniki
        details: "Located near the city center, the White Tower is..."
        id: 10
        area_shown:
        - description: Entity description here
          entity_id: 1
        - description: Entity description here
          entity_id: 1
      xml:
        name: interactive_map
    Interactive_Map_Entity:
      type: object
      properties:
        entity_id:
          type: integer
          format: int64
          example: 1
        description:
          type: string
          example: Entity description here
      example:
        description: Entity description here
        entity_id: 1
    Landmark_photos:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 16422
        name:
          type: string
          example: Top view of the Tower.
        image:
          type: array
          items:
            type: integer
            format: int64
            example: 255
        date:
          type: string
          example: 10th of August 2017
      example:
        date: 10th of August 2017
        image:
        - 255
        - 255
        name: Top view of the Tower.
        id: 16422
    Landmark_reviews:
      properties:
        review_id:
          type: integer
          format: int64
          example: 2
        review_text:
          type: string
          example: This landmark worths visiting...
        numOfStars:
          maximum: 5
          minimum: 1
          type: integer
          format: int64
          example: 2
        comments:
          type: string
          example: I agree with this review...
        date:
          type: string
          example: 15th of November 2023
      example:
        date: 15th of November 2023
        review_id: 2
        numOfStars: 2
        comments: I agree with this review...
        review_text: This landmark worths visiting...
    Review_comments:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 3
          text:
            type: string
            example: I loved the view from up there!
          author:
            type: string
            example: WiseWanderer
          date:
            type: string
            example: 9th of July 2024
    ReviewForRequestBody:
      description: A Review object as request body for http post
      type: object
      properties:
        review_id:
          type: integer
          format: int64
          minimum: 1
          example: 2
        review_text:
          type: string
          example: "This landmark worths visiting..."
        date:
          type: string
          example: "15th of November 2023"
        numOfStars:
          type: integer
          format: int64
          minimum: 0
          maximum: 5
          default: 0
          example: 0
        comments:
          type: array
          default: []
          example: []
      required:
        - review_id
        - review_text
        - date
      additionalProperties: false
    ReviewsArray:
      description: List of review object
      type: array
      items:
        $ref: '#/components/schemas/Review'
      example:
        - review_id: 2
          review_text: "This landmark worths visiting..."
          numOfStars: 2
          comments: 
            - id: 1
              text: "I aggre with this review..."
              author: "HappyVisitor"
              date: "16th of November 2023"
          date: "15th of November 2023"
        - review_id: 3
          review_text: "An unforgettable experience!"
          numOfStars: 5
          comments:
            - id: 2
              text: "The atmoshere was incredible."
              author: "WiseWanderer"
              date: "22th of November 2023"
            - id: 3
              text: "A must-visit landmark."
              author: "WorldExplorer"
              date: "22th of November 2023"
          date: "20th of November 2023"
        - review_id: 4
          review_text: "Not as expected, a bit underwhelming."
          numOfStars: 3
          comments:
            - id: 4
              text: "Could have been better organized."
              author: "LandmarkLover"
              date: "14th of November 2023"
            - id: 5
              text: "Was not as advertised."
              author: "WiseWanderer"
              date: "17th of November"
          date: "10th of November 2023"
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
  securitySchemes:
    landmarks_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://wanderwise.swagger.io/oauth/authorize
          scopes:
            write:landmarks: modify landmarks in your account
            read:landmarks: read your landmarks
    reviews_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://wanderwise.swagger.io/oauth/authorize
          scopes:
            write:reviews: modify reviews in your account
            read:reviews: read your reviews
    comments_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://wanderwise.swagger.io/oauth/authorize
          scopes:
            write:comments: modify comments in your account
            read:comments: read your comments
    experiences_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://wanderwise.swagger.io/oauth/authorize
          scopes:
            write:experiences: modify experiences in your account
            read:experiences: read your experiences
    photos_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://wanderwise.swagger.io/oauth/authorize
          scopes:
            write:photos: modify photos in your account
            read:photos: read your photos
